### ISSUE TITLE
Problem with copy/paste buffer

### ISSUE THREAD

**Issue by Peter2121** [Obsidian-StudiosInc/ecrire#25] opened 2017-11-26 13:39 UTC
When I paste something to Ecrire from another application (for example, from Firefox) and then close Ecrire - the source application (Firefox) craches. Sometimes, another application craches too (Thunderbird). I think that the management of copy/paste buffer in Ecrire is not correct, so it frees a memory region, used by another application.

**Comment by wltjr** [comment] 2017-11-26 18:41
That would be a EFL or elm_code issue. There is not really any copy/paste code. I just call those functions, [elm_code_widget_selection_copy](https://github.com/Obsidian-StudiosInc/ecrire/blob/master/src/bin/main.c#L535) and [elm_code_widget_selection_paste](https://github.com/Obsidian-StudiosInc/ecrire/blob/master/src/bin/main.c#L5490) , of elm_code. Also a [little bit](https://github.com/Obsidian-StudiosInc/ecrire/blob/master/src/bin/main.c#L624) for handling when to activate and de-activate the button.

I do not think upstream cares much about copy and paste. There are numerous issues there. Are you running Wayland. I am not sure about Wayland and copy and paste. I think that may have some bugs of its own that do not exist on X. Last I looked there was not much if any Wayland code in [elm_cnp](https://github.com/Enlightenment/efl/blob/master/src/lib/elementary/elm_cnp.c). Very likely a bug there.

I know there are some issues with GTK apps and copy and paste under X in general not ecrire specific. But never any crashing during copy/paste. That seems for sure like some EFL bug and maybe Wayland specific. Your good at finding these. Or why I do not run or mess with Wayland if you are running that. If X that will really suck and be a major regression or new issue... Not like EFL release do not bring new issues :)

**Comment by wltjr** [comment] 2017-11-26 19:25
Check out issue #11 The reason I mention that is it only does the duplicate paste when copying and pasting from outside ecrire into ecrire. It does something odd there. Thus that you are seeing a crash wih another application after copying pasting and closing ecrire. Seems like more issues on handling paste from outside an application.

I would think most everyone to be a big user of copy and paste. I am not sure EFL or E devs ever do that much. Seems to be many issues. Like losing paste buffer after closing an app. Copy something in terminology. Close it and the paste buffer you copied is gone... Main reason I use [clipboard](https://github.com/Obsidian-StudiosInc/clipboard). Which has tons of issues getting copy and paste all the time. Even before I removed X specific code and moved to elm_cnp. But many times I have no way to find out about a copy/paste event. Or able to grab and save that in clipboard history.

It makes doing any development really hard and discouraging. Given the numerous issues that seems like devs are either unaware, do not care, or haven't encountered for what ever reason. Which I kinda assume is usage. If they used this stuff they would be aware of more issues. Clearly few are using EDI. I could not see writing code with such issues. I use Ecrire mostly for notes and temporary text I do not care much about. Even for that its pretty unreliable due to issues as you know. That most all these exist in EDI. Clearly few are using that, or doing very little with it as to not hit the numerous bugs...

I am trying to help make things better, but they are making that very difficult vs being helpful. Really haven't gotten any help. Which says quite a lot given how much I am looking to do and contribute. I do not see others doing that who aren't already affiliated with E/EFL or Bohdi.... Maybe things will change and improve in time. Surely doing all I can to ensure that is the case. I wish that was the focus more than words, conduct, superficial bs stuff that doesn't make tech any better.... :)

**Comment by ApostolosB** [comment] 2017-11-26 19:39
Tried this on Wayland (xwayland firefox to ecrire) and everything works as expected. Also tried terminology to ecrire and again it works as expected. CnP is a different code path in wayland i think.

Move to wayland people (unless you have many monitors in which case you will have to wait a week or so to land in git or 1.21) 😛

**Comment by wltjr** [comment] 2017-11-26 19:48
I am in no rush for Wayland. I experience enough issues under X. I do have many monitors and hot plug, etc. I am pretty sure it will be more than a week. Definitely given issues that may arise once you can even run it on multiple displays and of varying resolution. elm_cnp has different hooks for X and Wayland. Still not ideal from a clipboard application perspective. Any issue with [clipboard](https://github.com/Obsidian-StudiosInc/clipboard) for the most part is a limitation in EFL.

I am not anti Wayland. I just know it took X decades to get where we are, yet it still has issues. I am not sure Wayland will solve all this, and likely to revisit many issues that were already resolved under X. Seems more a embedded single display solution. When you starting adding back all the features of X it it changes, and who knows where things will end up. Maybe just a tad better than X with various limitations. Like the whole controversial grabbing mouse and keyboard to ensure focus. That is changing and causing debate.

**Comment by Peter2121** [comment] 2017-11-26 23:02
I am on X as I am on FreeBSD. Wayland support is minimalist on FreeBSD for the moment, and I think that it's impossible to compile E with Wayland support on FreeBSD.
My version of EFL is 1.20.5, the issue #11 you mentioned is present :(
Hope the both issues will be fixed one day.

**Comment by wltjr** [comment] 2017-11-27 00:05
I think we are second class citizens being on X. I think X bugs are 2nd to Wayland bugs. Which wayland work I think is creating many of the X bugs. I get the feeling they rather stop supporting X sooner than later. No matter the practicality or impact. I think that is in part why Moshka exists. Stick to X, not really any work toward wayland. Also the external compositor aspect. I rather that be internal. Just have to do stuff to enable effects. @zmike was saying something about a module or layer that would allow compiz effects plugins to be used. He wrote something to support it. Or just have to write some effect plugins or something like that I cannot recall. Likely in a IRC log or email.

I thought some were running Wayland on FreeBSD not sure. i think at least 1 dev runs it. I need to check it out. If I bail from Gentoo that is where I am heading. I very much like their foundation, organization etc. I haven't looked at the Java stuff, but that could likely carry over. Most of my ebuilds I could translate to ports packages, etc. Tons of work but its the only real option for another from source. Not to mention non systemd, etc. I run openrc, though have no issues running elogind. Need to see about adding that to wayland as optional replacement or addition to consolekit. I dislike the amount of consolekit threads/processes. Otherwise pretty moot to me. But the rest of systemd, no thank you.

No clue on issues being fixed. Many have existed for months. I dislike having my own for that long though have some I am neglecting. Its discouraging when I go to fix things and run into a bunch of other issues along the way.... Not issues with my code but others and effects what I am doing so just messes it all up. Error output at times makes its hard to even know if its my code that's wrong or internal errors its crazy. But really seems focus is else where and/or all over the place. No direction organization, etc. Not sure anyone seems to care about over all QA. It all works for them and that is good enough...

Someday things will be fixed, though likely new issues along the way. When the fixing day will come... I hope sooner than later, but later it more likely sadly :(

**Comment by wltjr** [comment] 2018-02-22 15:31
@Peter2121 are you still experiencing this issue? I am not able to replicate.

If you are still experiencing this, is it just Firefox and Thunderbird or other apps? I assume non EFL apps like GTK etc. If it is just Mozilla applications that would be interesting.

**Comment by wltjr** [comment] 2018-08-03 02:51
@Peter2121 ping again, will close unless I hear otherwise. I am not able to replicate. Though do not copy and paste into Ecrire to much. Since I cannot via 3rd button which I use more than anything else.

**Comment by wltjr** [comment] 2018-08-19 21:35
Without further information and confirmation this still occurs. I am going to close this for now. Please file a new issue if it is still taking place. Thank you!

**Closed as completed by wltjr** 2018-08-19 21:35 UTC
Labels: bug, upstream bug
