### ISSUE TITLE
Blinking cursor not in the right place on start

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#33] opened 2018-06-04 08:25 UTC
##### Description
Description of issue

https://www.enlightenment.org/ss/display.php?image=e-5b14f696376180.05382213.png

##### Steps to reproduce
1. Just open ecrire. Happens only on start. If you focus/unfocus it goes away

##### System information
- EFL Version = git
- E Version = git
- X or Wayland = Wayland

**Comment by wltjr** [comment] 2018-06-04 13:23
That sounds like a regression in git. I feel like that was an issue long ago. I recall it being such. Can you check in elm_tests. I suspect it should be similar. Not sure about edi. Either way I do nothing with cursor placement. That is likely something with elm_code.

**Comment by wltjr** [comment] 2018-06-04 13:26
I reported this in https://phab.enlightenment.org/T5511. But then the cursor was in the toolbar area around New button. Seems you provided a screenshot at the time. Not sure if it is related. But more of the same from before it seems.

**Comment by wltjr** [comment] 2018-08-19 19:45
@ApostolosB can you see if this still occurs in EFL 1.21.0, or git. Thanks!

**Comment by ApostolosB** [comment] 2018-08-28 06:41
1.21.0 no. Git doesn't compile at the moment for me -for whatever reason- so i can't test there.

**Comment by wltjr** [comment] 2018-08-28 17:39
I assume you mean EFL git. If that is the case I will go ahead and close this as resolved. Since its fixed in 1.21.0. Thanks!

**Closed as completed by wltjr** 2018-08-28 17:39 UTC
Labels: bug, upstream bug
