### ISSUE TITLE
elm_code: Unable to scroll right for text selection of long lines

### ISSUE THREAD

**Issue by Peter2121** [Obsidian-StudiosInc/ecrire#15] opened 2017-10-22 18:57 UTC
When a line of text is longer than the horizontal size of Ecrire's window - the horizontal scroll automatically occurs on 'End' key pressing. But when the 'Shift' key is pressed in the same time (to select the text till the end of the line) - there is no horizontal scroll. The whole line is selected, but the beginning of the line is still shown.
Idem for the vertical scroll - going down (with 'PgDown' for example) and pressing 'Shift' at the same time, blocks scrolling down.

**Comment by wltjr** [comment] 2017-10-22 19:18
Thanks I [filed this with upstream T6221](https://phab.enlightenment.org/T6221) before having my [account disabled](https://phab.enlightenment.org/p/wltjr/) due to my interaction on that very task. elm_code has numerous issues that sadly effect ecrire. Not much I can do to resolve but wait for upstream to address.

**Comment by wltjr** [comment] 2017-10-22 19:30
Sounds like you discovered many more issues with scrolling in elm_code than just unable to scroll long lines to the right. I doubt upstream is aware of these other issues. You may want to file individual issues on each. Unable to scroll down while pressing shift. The end key button issue. I do not think that stuff will be fixed when they fix scrolling right.

**Comment by wltjr** [comment] 2017-11-24 18:37
Adding upstream so they are aware of issues
@Enlightenment @ajwillia-ms @zmike

**Comment by andydotxyz** [comment] 2018-07-24 09:18
Pretty sure this has been resolved upstream

**Comment by wltjr** [comment] 2018-07-24 13:42
Great thanks @ajwillia-ms! I will close it once EFL 1.21 is released. Thanks!

**Comment by wltjr** [comment] 2018-07-30 16:23
Confirmed resolved in 1.21, will close once released.

**Comment by wltjr** [comment] 2018-08-19 19:36
Able to scroll to the right on long lines. Only on that line, but that is better than before, closing.

**Closed as completed by wltjr** 2018-08-19 19:36 UTC
Labels: bug, upstream bug, upstream fixed
