### ISSUE TITLE
Resizing causes text selection

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#21] opened 2017-11-24 09:07 UTC
To rep:
Have a file with multiple lines of text.
Use the bottom right corner to resize the window.
Move the pointer in the text area
It selects the text.

ecrire-git efl 1.20.6& git

**Comment by wltjr** [comment] 2017-11-24 18:24
Not able to replicate maybe a regression in git. Can you see if this occurs with elm_tests/Elementary Tests -> Code Editor, Code Entry Markup, or others. Thanks!

Sounds like yet another elm_code bug...

**Comment by wltjr** [comment] 2017-11-24 18:37
Adding upstream so they are aware of issues
@Enlightenment @ajwillia-ms @zmike

**Comment by ApostolosB** [comment] 2017-11-24 20:37
Yes happens with Test -> Code editor

**Comment by wltjr** [comment] 2017-11-24 20:42
Great thanks for confirming!

**Comment by andydotxyz** [comment] 2017-11-24 21:27
I cannot replicate, perhaps misunderstanding the steps - please expand on what you mean by "Move the pointer in the text area" .

A video would be helpful, if possible.

**Comment by ApostolosB** [comment] 2017-11-24 21:34
@ajwillia-ms 
Open elm_test > open Code editor > Move pointer to the lower border to see the resize cursor >Resize > move the cursor from the bottom to the top bar. The text will become blue/selected.

**Comment by andydotxyz** [comment] 2017-11-24 21:37
I cannot replicate with those steps, sorry. There are no clicks or keyboard steps required?

**Comment by ApostolosB** [comment] 2017-11-24 21:57
http://www.filedropper.com/20171124234047
video file of the bug.

Also i have to remind you people that i am on wayland. If you can't rep it like that we probably have an input issue on WL.

**Comment by wltjr** [comment] 2017-11-24 22:01
@ApostolosB thanks much. I think with future bugs we may need to know wayland vs X. I will make up a basic bug template asking EFL version E version and X or Wayland. Though not sure E version matters. Using only EFL code nothing E specific. Not sure ecrire has been subject to any E related bugs or fixes, just EFL.

**Comment by andydotxyz** [comment] 2017-11-24 22:42
Thanks for the video.
I wonder if this is possibly an issue with e-wayland rather than elm_code in wayland.
Just a guess. Is it possible for you to try on another window manage to rule that out please?

**Comment by ApostolosB** [comment] 2017-11-24 22:53
Tried it on weston and i get the same behavior. So we rule out enlightenment having anything to do with it. On monday i'll discuss it with derek.

**Comment by wltjr** [comment] 2017-11-24 22:57
E has its own widgets and stuff. Only really if there was ecrire issues window manager related,title bar, positioning etc. Ecrire uses pure EFL code. It does not need E at all. You can run ecrire outside of E like Terminology. Just need EFL :)

**Comment by wltjr** [comment] 2018-02-21 03:36
I still cannot replicate this on X, EFL 1.20.7-pre. I think this is something Wayland and EFL specific, maybe a bug in EFL in Wayland.

@ApostolosB  Can you see if that happens on any of the multi-line editors in Elementary Tests. That would show if its general or elm_code specific. Either way I believe this to be Wayland specific. Unless you can test and replicate under X. Thanks!

**Comment by ApostolosB** [comment] 2018-03-12 15:03
https://phab.enlightenment.org/T6422
its this i believe

**Comment by wltjr** [comment] 2018-03-12 15:07
Ok thanks! To bad github does not have a field for URLs. I will keep an eye on that upstream task.

**Comment by andydotxyz** [comment] 2018-07-24 09:17
It looks like this was resolved upstream 4 months ago

**Comment by wltjr** [comment] 2018-07-24 13:42
Great thanks @ajwillia-ms! I will close it once EFL 1.21 is released. Thanks!

**Comment by wltjr** [comment] 2018-08-19 19:38
@ApostolosB can you confirm this is resolved. I do not believe I could ever replicate. It seems to be resolved upstream in 1.21.0 and git. Thanks!

**Comment by ApostolosB** [comment] 2018-08-28 06:43
Seems ok in 1.21.0.

**Comment by wltjr** [comment] 2018-08-28 12:45
Ok will close as resolved. If not I can re-open or file a new issue. Thanks!

**Closed as completed by wltjr** 2018-08-28 12:45 UTC
Labels: bug, upstream bug, upstream fixed
