### ISSUE TITLE
Hitting enter moves the pointer on the icon bar.

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#9] opened 2017-05-21 18:31 UTC
https://www.enlightenment.org/ss/display.php?image=e-5921dc4e2f2be6.21704835.png (on top of the new icon)

As the title describes.

**Comment by wltjr** [comment] 2017-05-21 18:43
I have seen that before and  I am pretty sure is an elm code bug. One I haven't ever reported myself yet. But I have seen the cursor be up in the menu many times. Sometimes it is there while you are typing. Thanks for the report, I had not had a chance to go after such myself. This one I think is elm code specific and I will open a related bug as such. Thanks for the screenshot!

**Comment by wltjr** [comment] 2017-05-21 18:46
Opened a upstream task [T5511](https://phab.enlightenment.org/T5511)

**Comment by wltjr** [comment] 2017-05-22 16:47
Confirmed on elm test code editor. Hitting enter on last line moves it to the first. Still in the editor, but likley because it has no elements between it and the top of the window.

**Comment by wltjr** [comment] 2017-07-21 01:39
This was fixed upstream for 1.19.2 and seems fixed in 1.20 beta 3. Can you confirm the same @ApostolosB? Thank you for your time checking!

**Comment by ApostolosB** [comment] 2017-07-24 13:33
Dont see this anymore with git since quite some time.

**Comment by wltjr** [comment] 2017-07-24 15:11
This was definitely fixed. Just waiting for EFL 1.20 to be released before I close. Then I will increase the EFL version build requirements, and close.

**Comment by wltjr** [comment] 2017-08-08 02:40
EFL 1.20.1 is out so closing. Will push a commit in a bit with minimum requirement for that version.

**Closed as completed by wltjr** 2017-08-08 02:40 UTC
Labels: bug
